# Generated by Django 4.1 on 2022-08-07 11:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Найменування')),
            ],
            options={
                'verbose_name': 'Найменування характеристики',
                'verbose_name_plural': 'Найменування характеристик',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Назва для пошуку')),
                ('title', ckeditor.fields.RichTextField(blank=True, max_length=4096, null=True, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Значення характеристик',
                'verbose_name_plural': 'Значення характеристик',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Загловок')),
                ('image', models.ImageField(max_length=512, upload_to='item', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='ItemAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Найменування')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='advantages/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Зображення властивостей товару',
                'verbose_name_plural': 'Зображення властивостей товару',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Найменування')),
                ('slug', models.SlugField(blank=True, max_length=512, null=True, verbose_name='Унікальний запис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='item', verbose_name='Зображення')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Альт картинки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товару',
            },
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_features', to='project.feature', verbose_name='Назва характеристики')),
                ('feature_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_features', to='project.featurevalue', verbose_name='Значення характеристики')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_features', to='project.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товару',
                'verbose_name_plural': 'Характеристики товару',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='advantages',
            field=models.ManyToManyField(blank=True, related_name='items', to='project.itemadvantage', verbose_name='Властивості'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.itemcategory', verbose_name='Категорія'),
        ),
    ]
