# Generated by Django 4.0.6 on 2022-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
    ]
