# Generated by Django 4.0.6 on 2022-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_item_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ціна'),
        ),
    ]
