# Generated by Django 4.0.6 on 2022-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(default='static', max_length=512, upload_to='item', verbose_name='Зображення'),
            preserve_default=False,
        ),
    ]
