# Generated by Django 4.0.6 on 2022-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_itemcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['ordering'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='ordering',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортування'),
        ),
    ]
