# Generated by Django 4.0.6 on 2022-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_itemcategory_options_itemcategory_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортування'),
        ),
    ]
