# Generated by Django 4.1 on 2022-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_itemcategory_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['ordering'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AddField(
            model_name='item',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортування'),
        ),
    ]
