# Generated by Django 4.1.2 on 2022-10-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_item_options_item_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='itemfeature',
            name='feature_value',
        ),
        migrations.RemoveField(
            model_name='itemfeature',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='FeatureValue',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemAdvantage',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.DeleteModel(
            name='ItemFeature',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
