# Generated by Django 4.1.2 on 2022-10-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_item_advantages_remove_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email'),
        ),
    ]
