# Generated by Django 4.1.2 on 2022-11-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_contact_comment_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('rate', models.FloatField(verbose_name='Курс')),
                ('code', models.FloatField(verbose_name='Код')),
                ('symbol', models.FloatField(verbose_name='Символ')),
            ],
        ),
    ]
