# Generated by Django 4.1.2 on 2022-11-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Рік')),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
