# Generated by Django 3.2.16 on 2025-04-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_year_delete_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-name'], 'verbose_name': 'Рік', 'verbose_name_plural': 'Роки'},
        ),
    ]
