# Generated by Django 4.1 on 2022-08-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Meta-title')),
                ('meta_descr', models.TextField(blank=True, null=True, verbose_name='Meta-description')),
                ('meta_key', models.TextField(blank=True, null=True, verbose_name='Meta-keys')),
                ('favico', models.ImageField(blank=True, max_length=512, null=True, upload_to='site/', verbose_name='Favico')),
                ('facebook', models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=512, null=True, verbose_name='Instagram')),
                ('mail', models.CharField(blank=True, max_length=512, null=True, verbose_name='Mail')),
                ('youtube', models.CharField(blank=True, max_length=512, null=True, verbose_name='Youtube')),
                ('youtube_video', models.CharField(blank=True, max_length=512, null=True, verbose_name='Youtube Video')),
                ('phone', models.CharField(blank=True, max_length=512, null=True, verbose_name='Phone')),
                ('price', models.FileField(blank=True, max_length=512, null=True, upload_to='site/', verbose_name='Price File')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='SitePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=512, null=True, verbose_name='Phone')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='s_content.site', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телефони',
                'verbose_name_plural': 'Телефони',
            },
        ),
    ]
