# Generated by Django 4.1.2 on 2022-10-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='site',
            name='youtube_video',
        ),
        migrations.DeleteModel(
            name='SitePhone',
        ),
    ]
