# Generated by Django 4.1.2 on 2022-10-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_content', '0002_remove_site_youtube_remove_site_youtube_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='price',
        ),
    ]
